### ISSUE TITLE
No items appearing in zotero search

### ISSUE THREAD

**Issue by carljoseph** [vyleung/logseq-logtero-plugin#13]
Set up with a basic .bib file. `/logtero` command pops up the search but nothing appears when I search for an item.

I've tried with a smaller .bib file, but still get the same problems. 

Any thoughts on how to debug this one?

**Comment by vyleung** [comment]
hi, this plugin only supports `.json` files. for `.bib` files, i'd recommend the [citation manager plugin](https://github.com/sawhney17/logseq-citation-manager)
