### ISSUE TITLE
Curious case of reference changing name

### ISSUE THREAD

**Issue by danieltomasz** [vyleung/logseq-logtero-plugin#3]
After creation of reference I have
`Pathania et al. 2021 Relating resting EEG power spectra to age-related differences in cognitive performance: An observational pilot study`
after reindexing files it becomes
`Relating resting EEG power spectra to age-related differences in cognitive performance: An observational pilot study`

Below the compressed bibliography file
[Pathania.bib.zip](https://github.com/vyleung/logseq-logtero-plugin/files/9105779/Pathania.bib.zip)

I am on Logseq 0.7.6, On mac, plugin verson v1.0.1
Pages created  earlier with previoius version of the plugin doesnt change names.

**Comment by danieltomasz** [comment]
I see it now
I set the tile of the note to ` {{author}} {{year}} {{title}}`
zotero property `{{title}}` collide with Logseq property `{{title}}` that setting the title for  the note, the note will  always be renamed because of that

Please maybe rename the output of  zotero property as `item-title`,`citation-title` or `zotero-title`, it might be confusing for the other users later

**Comment by vyleung** [comment]
that's an oversight on my part - thanks for catching this! i changed the property to `zotero-title` in [v.1.0.2](https://github.com/vyleung/logseq-logtero-plugin/releases/tag/v.1.0.2)
