### ISSUE TITLE
ZIP folder named incorrectly

### ISSUE THREAD

**Issue by davidjaggi** [vyleung/logseq-logtero-plugin#5]
The zip folder to download is named logseq-task-info-plugin. Shouldn't it be named logseq-logtero-plugin?

**Comment by vyleung** [comment]
yep, sorry about that! i've re-released [v.1.0.2](https://github.com/vyleung/logseq-logtero-plugin/releases/tag/v.1.0.2) w/ the appropriate zip folder name

**Comment by davidjaggi** [comment]
Perfect thanks. That's my record time to close an issue 🥇 .
